# Generated by Django 4.2.27 on 2026-01-22 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Klienci",
            fields=[
                ("idKlienta", models.AutoField(primary_key=True, serialize=False)),
                ("NazwaFirmy", models.CharField(max_length=100)),
                ("Adres", models.CharField(blank=True, max_length=100, null=True)),
                ("Miasto", models.CharField(blank=True, max_length=50, null=True)),
                ("Email", models.CharField(blank=True, max_length=100, null=True)),
                ("NIP", models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Pracownicy",
            fields=[
                ("idPracownika", models.AutoField(primary_key=True, serialize=False)),
                ("Imie", models.CharField(max_length=50)),
                ("Nazwisko", models.CharField(max_length=50)),
                ("Rola", models.CharField(max_length=50)),
                (
                    "ObszarZadania",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Produkty",
            fields=[
                ("idProduktu", models.AutoField(primary_key=True, serialize=False)),
                ("NazwaProduktu", models.CharField(max_length=200)),
                ("Jednostka", models.CharField(blank=True, max_length=20, null=True)),
                ("CenaBazowa", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "CenaKonkurencji",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StatusKlienta",
            fields=[
                (
                    "idStatusKlienta",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("Nazwa", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="StatusZadania",
            fields=[
                (
                    "idStatusZadania",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("Nazwa", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="TypUmowy",
            fields=[
                ("idTypUmowy", models.AutoField(primary_key=True, serialize=False)),
                ("Nazwa", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="TypZadania",
            fields=[
                ("idTypZadania", models.AutoField(primary_key=True, serialize=False)),
                ("Nazwa", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Zadania",
            fields=[
                ("idZadania", models.AutoField(primary_key=True, serialize=False)),
                ("DataPlanowana", models.DateTimeField(blank=True, null=True)),
                ("DataWykonania", models.DateTimeField(blank=True, null=True)),
                ("WynikNotatka", models.TextField(blank=True, null=True)),
                (
                    "idKlienta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.klienci"
                    ),
                ),
                (
                    "idPracownika",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.pracownicy"
                    ),
                ),
                (
                    "idStatusZadania",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.statuszadania",
                    ),
                ),
                (
                    "idTypZadania",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.typzadania",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Umowy",
            fields=[
                ("idUmowy", models.AutoField(primary_key=True, serialize=False)),
                ("Ilosc", models.IntegerField(blank=True, null=True)),
                ("DataZawarcia", models.DateTimeField(auto_now_add=True)),
                (
                    "KwotaUmowy",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("PrzedmiotUmowy", models.TextField(blank=True, null=True)),
                (
                    "idKlienta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.klienci"
                    ),
                ),
                (
                    "idPracownika",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.pracownicy"
                    ),
                ),
                (
                    "idProduktu",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.produkty",
                    ),
                ),
                (
                    "idTypUmowy",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.typumowy",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OsobyDecyzyjne",
            fields=[
                ("idOsoby", models.AutoField(primary_key=True, serialize=False)),
                ("Imie", models.CharField(blank=True, max_length=50, null=True)),
                ("Nazwisko", models.CharField(blank=True, max_length=50, null=True)),
                ("Stanowisko", models.CharField(blank=True, max_length=100, null=True)),
                ("Telefon", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "idKlienta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="osoby_decyzyjne",
                        to="api.klienci",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="klienci",
            name="idStatusKlienta",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.statusklienta",
            ),
        ),
    ]
