# Generated by Django 4.2.27 on 2026-01-26 23:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="produkty",
            name="StanMagazynowy",
            field=models.IntegerField(default=0),
        ),
    ]
